name: CI

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
  
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.x

            - name: Build App
              run: dotnet build -c Release -o /out

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: bin
                path: /out

    test:
        needs: build
        runs-on: windows-latest
        steps:
            - name: Download binary
              uses: actions/download-artifact@v3
              with:
                name: bin
                path: wc/bin

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.x

            - name: Execute Tests
              run: dotnet test wc/bin/*.UnitTests.dll



