name: CI

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
  
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 7.0.x

            - name: Build App
              run: dotnet build -c Release -o build

            - name: Execute Tests
              run: dotnet test build/*.UnitTests.dll

            - name: Publish App
              run: dotnet publish src/wc.Console/wc.Console.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:DebugType=embedded --self-contained true -o /publish

            - name: Rename Binary
              run: mv /publish/wc.Console.exe /publish/wc.exe

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: wc-win-x64
                path: /publish





